package com.github.reygnn.core.data

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import java.util.Base64
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Encrypts the private SSH key **at rest** with a non-exportable AES-256-GCM
 * key from the Android Keystore (hardware-backed where the device has a
 * TEE/StrongBox). The plaintext key never leaves app storage unencrypted; even
 * on a rooted device or a forensic dump the file is worthless without the
 * Keystore key — which cannot leave the device.
 *
 * On-disk format of the encrypted file: Base64 of `[12-byte IV ||
 * GCM-ciphertext+tag]`. The IV is freshly generated by the provider per
 * [encrypt].
 *
 * The [ALIAS] is **the same string** in all three apps, but that means
 * **no** shared key material: Android Keystore keys are bound to the
 * app UID, and each app (own `applicationId`, own sandbox)
 * owns its own key under this name. Lobber, Caster and
 * Prodder therefore each encrypt with their own key and must
 * onboard independently of one another — cross-app sharing would only
 * be possible via IPC (e.g. a signature-guarded ContentProvider) or a
 * single-app architecture.
 */
object KeyVault {

    private const val ANDROID_KEYSTORE = "AndroidKeyStore"
    private const val ALIAS = "ssh_tools_key_vault"
    private const val TRANSFORMATION = "AES/GCM/NoPadding"
    private const val IV_LENGTH = 12
    private const val GCM_TAG_BITS = 128

    private fun secretKey(): SecretKey {
        val ks = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        (ks.getEntry(ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build(),
        )
        return generator.generateKey()
    }

    /** Encrypts [plaintext] into `IV || ciphertext`. */
    fun encrypt(plaintext: String): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())
        val iv = cipher.iv
        require(iv.size == IV_LENGTH) { "Unexpected IV length ${iv.size}" }
        return iv + cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
    }

    /** Decrypts an `IV || ciphertext` blob produced by [encrypt]. */
    fun decrypt(blob: ByteArray): String {
        require(blob.size > IV_LENGTH) { "Blob too short for IV + ciphertext" }
        val iv = blob.copyOfRange(0, IV_LENGTH)
        val ciphertext = blob.copyOfRange(IV_LENGTH, blob.size)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, secretKey(), GCMParameterSpec(GCM_TAG_BITS, iv))
        return String(cipher.doFinal(ciphertext), Charsets.UTF_8)
    }
}

/**
 * Interprets the on-disk key blob and returns the plaintext PEM, or null if there
 * is none or it can't be recovered. Kept pure (no Android dependencies) so the
 * branching is unit-testable; the actual AES decrypt ([KeyVault.decrypt]) needs
 * the Android Keystore and is injected as [decrypt].
 *
 * - blank → null (no key stored yet)
 * - `-----`-prefixed → returned as-is (legacy plaintext PEM from before at-rest
 *   encryption; Base64 ciphertext never starts with `-`, so the case is
 *   unambiguous, and the next `saveKey` rewrites it encrypted)
 * - otherwise → Base64-decode + [decrypt]; on failure (a tampered blob = GCM tag
 *   mismatch, a wiped Keystore key, or malformed Base64) report via [onError] and
 *   return null. The blob is then unrecoverable and re-onboarding is required.
 *   See AUDIT V8/V11.
 */
internal fun decodeKeyBlob(
    raw: String,
    decrypt: (ByteArray) -> String,
    onError: (Throwable) -> Unit = {},
): String? {
    val trimmed = raw.trim()
    if (trimmed.isEmpty()) return null
    if (trimmed.startsWith("-----")) return trimmed
    return runCatching { decrypt(Base64.getDecoder().decode(trimmed)) }
        .getOrElse { onError(it); null }
}
