package com.github.reygnn.core.data

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Encrypts the private SSH key **at rest** with a non-exportable AES-256-GCM
 * key from the Android Keystore (hardware-backed where the device has a
 * TEE/StrongBox). The plaintext key never leaves app storage unencrypted; even
 * on a rooted device or a forensic dump the file is worthless without the
 * Keystore key — which cannot leave the device.
 *
 * On-disk format of the encrypted file: Base64 of `[12-byte IV ||
 * GCM-ciphertext+tag]`. The IV is freshly generated by the provider per
 * [encrypt].
 *
 * Ein einzelner Alias für alle Apps — alle drei teilen denselben
 * kryptographischen Schlüssel, sodass ein einmal eingerichtetes SSH-Keypair
 * ohne erneutes Onboarding in Lobber, Caster und Prodder nutzbar ist.
 */
object KeyVault {

    private const val ANDROID_KEYSTORE = "AndroidKeyStore"
    private const val ALIAS = "ssh_tools_key_vault"
    private const val TRANSFORMATION = "AES/GCM/NoPadding"
    private const val IV_LENGTH = 12
    private const val GCM_TAG_BITS = 128

    private fun secretKey(): SecretKey {
        val ks = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        (ks.getEntry(ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build(),
        )
        return generator.generateKey()
    }

    /** Encrypts [plaintext] into `IV || ciphertext`. */
    fun encrypt(plaintext: String): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())
        val iv = cipher.iv
        require(iv.size == IV_LENGTH) { "Unexpected IV length ${iv.size}" }
        return iv + cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
    }

    /** Decrypts an `IV || ciphertext` blob produced by [encrypt]. */
    fun decrypt(blob: ByteArray): String {
        require(blob.size > IV_LENGTH) { "Blob too short for IV + ciphertext" }
        val iv = blob.copyOfRange(0, IV_LENGTH)
        val ciphertext = blob.copyOfRange(IV_LENGTH, blob.size)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, secretKey(), GCMParameterSpec(GCM_TAG_BITS, iv))
        return String(cipher.doFinal(ciphertext), Charsets.UTF_8)
    }
}
